# Generated by Django 3.1 on 2023-12-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0008_update_jsonfield_for_django_31'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logentry',
            table='auditlog_logentry_historical',
        ),
    ]
